### ISSUE TITLE
LETS GOOOO TU FAIS DU PYTHON

### ISSUE THREAD

**Issue by foodwithfire** [YouLeGamer/python-experiments#1]
Bon mon gars j'ai vu ton "issue" ou tu m'informais que tu te mettais a python et jvais pas tcacher, cette nouvelle me fût fort exquise, goutue même :O dcp la jvais te donner un ptit tip par rapport aux classes : 
pas besoin de faire des fonctions qui donnent par ex le pseudo du joueur:

class Player:
--def __init__(self, p):
----self.pseudo = p
--def get_pseudo(self):
----return self.pseudo

(jmets des "-" psq y'a pas de tabs dans les comment :'( )
 et oé c inutile tema la dingz:

firefood = Player("firefood")

Player c une classe avec un paramètre p qui dans ce cas la est "firefood"
Au lieu de faire firefood.get_pseudo pour obtenir le pseudo...... ba y'a juste a faire [object].[variable] dcp la c firefood.pseudo... é oé c very simple en éfé :p 

print(firefood.pseudo + " est un bg")

voila ct un extrait des cours du professeur food j'espere que jt'ai appris qql chose é bye

ps : prout

**Comment by YouLeGamer** [comment]
alors bonsoar professeur food
tout d'abord ui je me met au python tro bien
ensuite merci pour le tip jété pa o couran
et enfin ba déso j'étais afk ba ui ba je regarde pa minecraft quand jdev :/
jespèr que tu te co demain :D
comme je commence à 10h30 je profiterai du matin pour dev (bawé on met le temps à profit) et voala
bon soaré 

:D
